pondproject/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


// Route::group(['prefix' => 'admin'], function () {
//     Voyager::routes();
// });

// Route::get('/tieritems',[App\Http\Controllers\TierItemsController::class,'all']);
// Route::get('/reflection',[App\Http\Controllers\ReflectionController::class,'all']);
Route::resource('tasks', TaskController::class);
Route::resource('tieritems',App\Http\Controllers\TierItemsController::class);
Route::resource('reflection',App\Http\Controllers\ReflectionController::class);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/index', function () {
    return view('index');
});

pondproject/resources/views/old_content/about.blade.php
<?php 
if(($taskcompnum != 0)&&(count($task) != 0)){
  $prog = round((($taskcompnum/count($task))*100));
}
else{
  $prog = 0;
}
 ?>
<!-- ======= Tasks Section ======= -->
<section id="tasks" class="about skills">
  <div class="container">

    <div class="section-title">
      <h2>TASKS</h2>
    </div>

<!-- Modals -->  
@include('old_content.modals.add_modal')
@include('old_content.modals.edit_modal')


<?php if(count($task) != 0){?>
  <div class="row skills-content">
<div class="col-lg-12" data-aos="fade-up">

  <div class="progress" >
    <span class="skill">Your Progress: <i class="val">
    <?php 
      
      echo $prog.'%';
      
      ?></i></span>
    <div class="progress-bar-wrap" >
      <div class="progress-bar" role="progressbar" aria-valuenow="<?php echo $prog; ?>" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
  </div>
      
</div>

<?php } 
    else{?>
      <div class="section-title" style="margin: 5%; text-align: center;">
      <p>&nbsp&nbsp&nbspNo tasks!</p>
      </div>
      <?php   }?>


</div>
         
   
    <!-- Button to Open the Modal -->
      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#ModalLoginForm">
        Add task
      </button>
      <br> </br>

    <!-- Modal HTML Markup -->
    <div class="grid-container"> 
      <?php
      // $modals = array( 'a', 'b', 'c', 'd', 'e' );// Set the array
      
      foreach( $task as $tasks ):
      ?>

      @include('old_content.modals.tierunlocked')
   
      
      

        <div class="card" style="max-width: 300px;min-width: 300px; height:300px; ">
      
      <div class="card-body" >
        <h5 class="card-title">{{$tasks->title}}</h5>
        <p class="round3" ></p>
        <p class="card-text">{{$tasks->detail}}</p>
        <p class="card-text" id="deadline">{{$tasks->deadline}}</p>
        <input class="test" type="hidden" value="{{$tasks->deadline}}"></input>
        <input class="task_status" type="hidden" value="{{$tasks->isCompleted}}"></input>

        <form action="{{route('tasks.update',$tasks->id)}}" method="post" >
          @method('patch')
          @csrf
            <button type="submit" class="btn btn-primary btn-sm presscompleted" data-toggle="modal" data-target="#exampleModalLong"
              onClick="{{TaskController::addPoints()}} check()">
              Complete 
            </button> 
        </form>



        <a class="btn btn-primary btn-sm" id="edit-task" data-toggle="modal" data-id="{{$tasks->id}}">
         Edit
        </a>

        <form action="{{ route('tasks.destroy', $tasks->id ) }}" method="POST">
                @csrf
                @method('delete')
                <button type="submit" href="" class="btn md-5 btn-danger btn-sm">Delete</button>
                @csrf
        </form>

          </div>
  </div>   
       
        
        
   

    <?php
  
      endforeach;
    ?>
  </div>
  </div>
</section>


<script>

 var test = document.querySelectorAll("p.round3"),i;
 var dline= document.querySelectorAll("input.test");
 var tid = document.querySelectorAll("input.task_status");
 var completed = document.querySelectorAll(".presscompleted"),j;
 var today = new Date();
 var deadline;
 
 if(test.length){
  
  for( i=0; i<test.length; i++){
     
     deadline = new Date(dline[i].value);
    //  alert(deadline + " > " + today + " is "+(deadline>today));
    if(today>deadline){
      test[i].style.backgroundColor= "red";
      test[i].innerHTML = "overdue";
      <?php TaskController::delPoints();?>
    }
    else{
      test[i].style.backgroundColor= "green";
      test[i].innerHTML = "ongoing";
    }

  }
 }
 
 for(j=0; j<completed.length; j++){
  //  alert("task #"+index+" completed!");
   if(tid[j].value == 1){
    completed[j].disabled = true;
    completed[j].style.backgroundColor = "#98a3b5";
    completed[j].style.borderColor = "#656970";
    test[j].style.backgroundColor= "#3c81fa";
    test[j].innerHTML = "completed";
   
   }
   
 }

 function check(){
    <?php TaskController::addLvlPoints($prog); ?>
 }

 $(document).ready(function () {
/* Edit task */
$('body').on('click', '#edit-task', function () {
var task_id = $(this).data('id');
$.get('tasks/'+task_id+'/edit', function (data) {
$('#edittask').modal('show');
$('#taskid').val(data.id);
$('#title').val(data.title);
$('#detail').val(data.detail);
$('#date').val(data.deadline);
})
});
});

</script>

pondproject/resources/views/old_content/contact.blade.php
<!-- ======= Settings Section ======= -->
<section id="settings" class="contact">
  <div class="container">

    <div class="section-title">
      <h2>ACHIEVEMENTS</h2>
      <p>Check out our achievement badges that will be ranked according to your accessibility on the TOP 5 of Hall of Fame!</p>
    </div>


    <h3>Ranks</h3>
    <div class="row badges-container" style="text-align:center" data-aos="fade-up" data-aos-delay="100">


      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
         <!--example-->
          <img src="assets/img/achievements/novince-badge.png?ver=2" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>
  
      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="assets/img/achievements/intermediate-badge.png?ver=2" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="assets/img/achievements/advance-badge.png?ver=2" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="assets/img/achievements/expert-badge.png?ver=2" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

    </div>

    <h3>HOF Achievements</h3>
    <div class="row badges-container" style= "text-align:center" data-aos="fade-up" data-aos-delay="100">
      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="assets/img/achievements/ruby-badge.png?ver=2" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="assets/img/achievements/topaz-badge.png?ver=2" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="assets/img/achievements/diamond-badge.png?ver=2" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="assets/img/achievements/overachiever.png?ver=2" class="img-fluid" alt="" style="width:100%"> 
        </div>
      </div>

      <div class="col-lg-4 col-md-6 badges-item">
        <div class="">
          <img src="" class="img-fluid" alt="" style="width:60%"> 
        </div>
      </div>

    </div>

    <!-- <div class="row" data-aos="fade-in">

      <div class="col-lg-5 d-flex align-items-stretch">
        <div class="info">
          <div class="address">
            <i class="icofont-google-map"></i>
            <h4>Location:</h4>
            <p>A108 Adam Street, New York, NY 535022</p>
          </div>

          <div class="email">
            <i class="icofont-envelope"></i>
            <h4>Email:</h4>
            <p>info@example.com</p>
          </div>

          <div class="phone">
            <i class="icofont-phone"></i>
            <h4>Call:</h4>
            <p>+1 5589 55488 55s</p>
          </div>

          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen></iframe>
        </div>

      </div>

      <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
        <form action="forms/contact.php" method="post" role="form" class="php-email-form">
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="name">Your Name</label>
              <input type="text" name="name" class="form-control" id="name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
              <div class="validate"></div>
            </div>
            <div class="form-group col-md-6">
              <label for="name">Your Email</label>
              <input type="email" class="form-control" name="email" id="email" data-rule="email" data-msg="Please enter a valid email" />
              <div class="validate"></div>
            </div>
          </div>
          <div class="form-group">
            <label for="name">Subject</label>
            <input type="text" class="form-control" name="subject" id="subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
            <div class="validate"></div>
          </div>
          <div class="form-group">
            <label for="name">Message</label>
            <textarea class="form-control" name="message" rows="10" data-rule="required" data-msg="Please write something for us"></textarea>
            <div class="validate"></div>
          </div>
          <div class="mb-3">
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your message has been sent. Thank you!</div>
          </div>
          <div class="text-center"><button type="submit">Send Message</button></div>
        </form>
      </div>

    </div>

  </div> -->
</section><!-- End Contact Section -->

pondproject/resources/views/old_content/facts.blade.php
<!-- ======= Facts Section ======= -->

<section id="pond" class="facts">
  <div class="container">

    <div class="section-title">
      <h2>MY POND</h2>
      <p>Preview your decorated Pond here and expand your creativity! p/s: draw something on canvas.</p>
    </div>
    <button type="button" class="collapsible">Items</button>
        <div class="content">

          <?php foreach($refl as $claimeditems):?>
            <div class="drag-drop" id="select" data-tooltip="<?php echo $claimeditems->content;?>"data-tooltip-location="right" data-id="{{$claimeditems->id}}"> 
              <img src=<?php echo $claimeditems->item; ?>>
            </div>         
          <?php endforeach; ?>
        </div>

      <p id="add"> 



    <div id="outer-dropzone" class="dropzone">
 
      <canvas class="rainbow-pixel-canvas"></canvas>

      </div>
    </div>

</section><!-- End Facts Section -->

<script>
  var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}

$(document).ready(function () {
/* Edit task */
$('body').on('click', '#select', function () {
  var itemid = $(this).data('id');
    $.get('reflection/'+itemid+'/edit', function (data) {
      $('#add').after('<div id="yes-drop" class="drag-drop" data-tooltip="'+data.content+'"> <img src="'+data.item+'" id="draggable"></div>');
      })
  });
});

</script> 

pondproject/resources/views/old_content/hero.blade.php
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
    <div class="hero-container" data-aos="fade-in">
      <h1>Welcome to Pond</h1>
      <p>Pond is&nbsp<span class="typed" data-typed-items=" fun, easy, your #1 tasks manager"></span></p>
      @guest
            @if (Route::has('login'))
                <button type='button' class="">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </button>
            @endif
                            
            @if (Route::has('register'))
                 <button type='button' class="">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                 </button>
            @endif
           @else
           <p>Hello&nbsp{{ Auth::user()->name }}&#10024;</p> <br>
           <p>You are rank &nbsp{{TaskController::getLevel()}}</p>
           <button type='button' class="">
           <a class="dropdown-item" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                {{ __('Logout') }}
          </a>
          </button>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
          </form>
          <button type='button'><a href="/tasks">Go to Home</a></button>
      @endguest
    </div>
  </section>
  <!-- End Hero -->

pondproject/resources/views/old_content/index.blade.php
@extends('about')

@section('main')
      <div class="row">
        <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Title</h5>
            <p class="card-text">Task activities.</p>
            <!--<a href="#" class="btn btn-primary">Complete</a>-->

            <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModalLong">
              Complete <?php echo $i;?>
              </button>

            <a href="#" class="btn btn-info btn-sm">Edit</a>

            @foreach($tasks as $tasks)
            <div class="card">
              <div class="card-body">
                <div class="card-title">
                  <p>{{$tasks->title}}</p>
                </div>

                <div class="card-text">
                  <p>{{$tasks->detail}}</p>
                  <p>{{$tasks->deadline}}</p>
                </div>
              </div>
            </div>
            @endforeach

          </div>
        </div>
      </div>
@endsection

pondproject/resources/views/old_content/portfolio.blade.php
<!-- ======= HOF Section ======= -->
<section id="hof" class="portfolio section-bg">
  <div class="container">

    <div class="section-title">
      <h2>POND SHOP</h2>
      <p> Complete every tasks and increase your points to unlock each Tier for upgraded icons! </p>
    </div>

    <div class="row" data-aos="fade-up">
      <div class="col-lg-12 d-flex justify-content-center">
        <ul id="portfolio-flters">
          
          <?php $unlocked = array();?>
          @if($currPoints >= 100)
          <?php array_push($unlocked,"filter-t1");?>
          <li data-filter=".filter-t1">Tier 1</li>
            @if($currPoints >= 200)
            <?php array_push($unlocked,"filter-t2");?>
            <li data-filter=".filter-t2">Tier 2</li>
              @if($currPoints >= 300)
              <?php array_push($unlocked,"filter-t3");?>
              <li data-filter=".filter-t3">Tier 3</li>
                @if($currPoints >= 400)
                <?php array_push($unlocked,"filter-t4");?>
                <li data-filter=".filter-t4">Tier 4</li>
                  @if($currPoints >= 500)
                  <?php array_push($unlocked,"filter-t5");?>
                  <li data-filter=".filter-t5">Tier 5</li>
                  @endif
                @endif
              @endif
            @endif
          @endif

        </ul>
      </div>
    </div>
    @include('old_content.modals.claimitem')
    <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="100">
    <?php 

    foreach($items as $item): 
      
      for($i=0; $i<count($unlocked); $i++){
        if($item->tier == $unlocked[$i]){ ?>
           
        <div class="col-lg-4 col-md-6 portfolio-item <?php echo $item->tier; ?>">
          <div class="portfolio-wrap">
            <img src="<?php echo $item->src; ?>" class="img-fluid" alt="">
            <div class="portfolio-links">
              <a id="claim-item" data-toggle="modal" data-id="{{$item->id}}"><i class="bx bx-plus"></i></a>
              <a href="portfolio-details.html" title="More Details"><i class="bx bx-link"></i></a>
            </div>
          </div>
        </div>

    <?php } 
    
    }
    endforeach; ?>
     
    </div>

  </div>
</section><!-- End Portfolio Section -->

<script>
$(document).ready(function () {
/* Edit task */
$('body').on('click', '#claim-item', function () {
var item_id = $(this).data('id');
$.get('tieritems/'+item_id+'/edit', function (data) {
$('#claimitem').modal('show');
$('#itemimage').attr("src",data.src);
$('#item').val(data.src);
})
});
});
</script>

pondproject/resources/views/old_content/resume.blade.php
<!-- =======Calendar Section ======= -->
<section id="calendar" class="resume">
  <div class="container">

    <div class="section-title">
      <h2>CALENDAR</h2>

    </div>

    <div id='calendar'></div>

</div>
<script>
 var eventList = [];
 var task;

document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');
  // var list = 
 
  var calendar = new FullCalendar.Calendar(calendarEl, {
    themeSystem: 'bootstrap',
    initialView: 'dayGridMonth',
    initialDate: '2021-01-07',
    headerToolbar: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay'
    },
    events: <?php echo $encoded;?>
  });

  calendar.render();
});

    </script>



   <!-- <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
     <div class="row">
      <div class="col-lg-6" data-aos="fade-up">
        <h3 class="resume-title">Summary</h3>
        <div class="resume-item pb-0">
          <h4>Alex Smith</h4>
          <p><em>Innovative and deadline-driven Graphic Designer with 3+ years of experience designing and developing user-centered digital/print marketing material from initial concept to final, polished deliverable.</em></p>
          <ul>
            <li>Portland par 127,Orlando, FL</li>
            <li>(123) 456-7891</li>
            <li>alice.barkley@example.com</li>
          </ul>
        </div>

        <h3 class="resume-title">Education</h3>
        <div class="resume-item">
          <h4>Master of Fine Arts &amp; Graphic Design</h4>
          <h5>2015 - 2016</h5>
          <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
          <p>Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero voluptatum qui ut dignissimos deleniti nerada porti sand markend</p>
        </div>
        <div class="resume-item">
          <h4>Bachelor of Fine Arts &amp; Graphic Design</h4>
          <h5>2010 - 2014</h5>
          <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
          <p>Quia nobis sequi est occaecati aut. Repudiandae et iusto quae reiciendis et quis Eius vel ratione eius unde vitae rerum voluptates asperiores voluptatem Earum molestiae consequatur neque etlon sader mart dila</p>
        </div>
      </div>
      <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
        <h3 class="resume-title">Professional Experience</h3>
        <div class="resume-item">
          <h4>Senior graphic design specialist</h4>
          <h5>2019 - Present</h5>
          <p><em>Experion, New York, NY </em></p>
          <ul>
            <li>Lead in the design, development, and implementation of the graphic, layout, and production communication materials</li>
            <li>Delegate tasks to the 7 members of the design team and provide counsel on all aspects of the project. </li>
            <li>Supervise the assessment of all graphic materials in order to ensure quality and accuracy of the design</li>
            <li>Oversee the efficient use of production project budgets ranging from $2,000 - $25,000</li>
          </ul>
        </div>
        <div class="resume-item">
          <h4>Graphic design specialist</h4>
          <h5>2017 - 2018</h5>
          <p><em>Stepping Stone Advertising, New York, NY</em></p>
          <ul>
            <li>Developed numerous marketing programs (logos, brochures,infographics, presentations, and advertisements).</li>
            <li>Managed up to 5 projects or tasks at a given time while under pressure</li>
            <li>Recommended and consulted with clients on the most appropriate graphic design</li>
            <li>Created 4+ design presentations and proposals a month for clients and account managers</li>
          </ul>
        </div>
      </div>
    </div>

  </div> -->
</section><!-- End Resume Section -->

pondproject/resources/views/old_content/services.blade.php
<!-- ======= Shop Section ======= -->
<section id="shop" class="services">
  <div class="container">

    <div class="section-title">
      <h2>HALL OF FAME</h2>
      <p> Welcome to the Hall of Fame where you can publish your decorated pond and achieve badges based on your views and likes!</p>
    </div>

    <div class="row">
      <div class="col-md">
        <div class="card ">
          <div class="card-header">
            <h4 class="card-title">Hall Of Fame</h4>
          </div>

          <div class="card-body">
            <div class="table-responsive">
              <table class="table tablesorter " id="">
                <thead class=" text-primary">
              <tr>
                <th class="text">
                  Players
                </th>
                <th class="text-center">
                  Scores
                </th>
              </tr>
                </thead>
                <tbody>
                
                <?php for($i=0; $i<sizeof($hof['names']); $i++){ ?>
                <tr>
                <td class="text">
                <!-- user names -->
                <?php echo $hof['names'][$i]['alias']; ?> 
                &nbsp &nbsp &nbsp &nbsp
                </td>
                <td class="text-center">
                <!-- user scores -->
                <?php echo $hof['scores'][$i]; ?> 
                </td>
                <tr>
                <!-- <br> -->
                <?php } ?>
                
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
<!-- 
    <div class="row" id="gallery" data-toggle="modal" data-target="#exampleModal"> 
    
      <div class="col-12 col-sm-6 col-lg-3">
        <img class="w-100" src="assets/img/HOF/pond-1.png" data-target="#carouselExample" data-slide-to="0">
      </div>
  
      <div class="col-12 col-sm-6 col-lg-3">
        <img class="w-100" src="assets/img/HOF/pond-2.png" data-target="#carouselExample" data-slide-to="1">
      </div>
    
      <div class="col-12 col-sm-6 col-lg-3">
        <img class="w-100" src="assets/img/HOF/pond-3.png" data-target="#carouselExample" data-slide-to="2">
      </div>
  
      <div class="col-12 col-sm-6 col-lg-3">
        <img class="w-100" src="assets/img/HOF/pond-4.jpg" data-target="#carouselExample" data-slide-to="3">
      </div>

      <div class="col-12 col-sm-6 col-lg-3">
        <img class="w-100" src="assets/img/HOF/pond-5.png" data-target="#carouselExample" data-slide-to="4">
      </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        
      Carousel markup: https://getbootstrap.com/docs/4.4/components/carousel/
      <div id="carouselExample" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="assets/img/HOF/pond-1.png">
            </div>

            <div class="carousel-item">
              <img class="d-block w-100" src="assets/img/HOF/pond-2.png">
            </div>

            <div class="carousel-item">
              <img class="d-block w-100" src="assets/img/HOF/pond-3.png">
            </div>

            <div class="carousel-item">
              <img class="d-block w-100" src="assets/img/HOF/pond-4.png">
            </div>

            <div class="carousel-item">
              <img class="d-block w-100" src="assets/img/HOF/pond-5.png">
            </div>

          </div>
          <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> -->
    <!--<div class="row">
      <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
        <div class="icon"><i class="icofont-computer"></i></div>
        <h4 class="title"><a href="">Lorem Ipsum</a></h4>
        <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
      </div>
      <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
        <div class="icon"><i class="icofont-chart-bar-graph"></i></div>
        <h4 class="title"><a href="">Dolor Sitema</a></h4>
        <p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>
      </div>
      <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
        <div class="icon"><i class="icofont-earth"></i></div>
        <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
        <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
      </div>
      <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
        <div class="icon"><i class="icofont-image"></i></div>
        <h4 class="title"><a href="">Magni Dolores</a></h4>
        <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
      </div>
      <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
        <div class="icon"><i class="icofont-settings"></i></div>
        <h4 class="title"><a href="">Nemo Enim</a></h4>
        <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
      </div>
      <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="500">
        <div class="icon"><i class="icofont-tasks-alt"></i></div>
        <h4 class="title"><a href="">Eiusmod Tempor</a></h4>
        <p class="description">Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi</p>
      </div>
    </div> -->

  </div>
</section><!-- End hall of fame Section -->

pondproject/resources/views/old_content/skills.blade.php
<!-- ======= Skills Section ======= -->
<!-- <section id="skills" class="skills section-bg">
  <div class="container">
    <div class="row skills-content">

      <div class="col-lg-6" data-aos="fade-up">

        <div class="progress">
          <span class="skill">Your Progress: <i class="val"><?php echo count($task);?></i></span>
          <div class="progress-bar-wrap">
            <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>

       
      </div>

    </div>

  </div> -->
</section><!-- End Skills Section -->